version: '3'
services:
  web:
      build: .
      ports:
        - "5000:5000"
      volumes:
        - .:/code
  postgres:
    image: postgres:9.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
    volumes:
      - ~/Data/Postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: "foxylion/pgadmin4"
    restart: always
    ports:
      - "9050:80"
    volumes:
      - pgadmin:/data
volumes:
  pgadmin:



